---
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: -validate-settings.yml
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        users: []
        teams: []
