repository:
  name: api
  description: repository with branch protection
  private: true
  has_issues: true
  has_projects: false
  has_wiki: false

branches:
  - name: main
    protection:
      required_status_checks:                 
        strict: true                          
        contexts:                              
          - validate-settings.yml 
      enforce_admins: true                    
      required_pull_request_reviews:
        dismissal_restrictions: {}
        dismiss_stale_reviews: true           
        require_code_owner_reviews: true      
        required_approving_review_count: 1    
      restrictions: null                      
