---
repository:
  name: api
  description: Sample repo with Probot settings
  private: true
  delete_branch_on_merge: true
  has_issues: true
  has_projects: false
  has_wiki: false

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
      restrictions: null
